routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/users', 'UserController@index');
Route::resource('/users', 'UserController');
Route::GET('/GetDesignations', 'UserController@GetDesignations')->name('GetDesignations');
Route::GET('/GetRegions', 'UserController@GetRegions')->name('GetRegions');
Route::GET('/GetDistrict', 'UserController@GetDistrict')->name('GetDistrict');
Route::GET('/GetOffice', 'UserController@GetOffice')->name('GetOffice');
Route::GET('/GetUserType', 'UserController@GetUserType')->name('GetUserType');

/* vehicle section */
Route::resource('/vehicle-management', 'VehicleController');
Route::resource('/custody-management', 'CustodyController');
//Route::get('ajax/request', 'AjaxController');

/* rti section */
Route::resource('/rti-new-application', 'RtiController');
Route::resource('/rti-appeal-application', 'RtiAppealController');
Route::resource('/rti-public-authority', 'RtiPublicAuthorityController');
Route::resource('/rti-penalty', 'RtiPenaltyController'); 
Route::GET('/GetOfficersByRegion', 'UserController@GetOfficersByRegion')->name('GetOfficersByRegion');   
Route::GET('/GetOfficersByDistrict', 'UserController@GetOfficersByDistrict')->name('GetOfficersByDistrict');
Route::GET('/GetOfficersByOffice', 'UserController@GetOfficersByOffice')->name('GetOfficersByOffice');
Route::resource('/rti-public-information-officer', 'RtiPublicInformationOfficerController');
Route::resource('/rti-diciplinary-action', 'RtiDiciplinaryActionController');
/* end rti section */
/*hr */
Route::resource('/hr-employee-details', 'HrEmployeeDetailsController'); 
Route::resource('/hr-transfer-application', 'HrTransferApplicationSubmissionController');
Route::resource('/hr-training-register', 'HrTrainingRegister');
Route::resource('/hr-reports', 'HrReportsController');
/*end hr */
/*file disposal */
Route::resource('/file-disposal', 'FileDisposalController');

/*end file disposal*/
/* custom report */
Route::resource('/custom-report', 'CustomReportController');
/* end custome report*/
/* monthly programs*/

Route::resource('/monthly-programms', 'MonthlyProgramsController');
/* end monthly programs*/
Route::resource('/md-verification', 'MasterDataVerificationController');
Route::resource('/md-fi-complaint-inspection', 'MasterDataFieldComplaintInspectionController');
Route::resource('/md-fi-surprise-inspection', 'MasterDataFieldSurpriseInspectionController');
Route::resource('/md-fi-redeem-inspection', 'MasterDataFieldComplaintRedeemInspectionController');

resources/views/hr-employee-details.blade.php
<!-- @extends('layouts.app') -->
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">HR EMPLOYEE DETAILS</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group" role="group" aria-label="Basic example">
                        <a href="{{route('hr-employee-details.create')}}" class="float-right btn-right">
                        <button type="button" class="btn btn-secondary" title="Add new user" data-original-title="Add New User">
                        <i class="fa fa-plus" aria-hidden="true"></i>ADD EMPLOYEE DETAILS</button>
                        </a>
                    </div>    
                </div>   
            </div> 
            <div class="row">
                <div class="col-lg-12">
                @if (Session()->has('message'))
                <div class="alert alert-dismissable alert-success" id="flash-message">
                <button type="button"class="close"data-dismiss="alert"aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <strong>
               {{ Session::get('message') }}
                </strong>
                </div>
                @endif
                </div>
            </div>    
            <div class="row" style="min-height:800px;">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Employees in MIS
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Pen</th>
                                            <th>Designation</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php($count=1)
                                        @foreach($data as $dt)
                                        <tr class="odd gradeX">
                                            <td>{{$count}}</td>
                                            <td>{{$dt['emp_name']}}</td>
                                            <td>{{$dt['emp_pen']}}</td>
                                            <td>{{$dt['designation']}}</td>
                                            <td>
                                                <a class="add btn btn-default" href="{{route('hr-employee-details.edit',$dt['employee_id'])}}"  title="Edit" data-toggle="tooltip"><i class="fa fa-edit "></i></a>&nbsp;&nbsp;
                                                <a class="edit btn btn-default" href="{{route('hr-employee-details.show',$dt['employee_id'])}}" title="View" data-toggle="tooltip"><i class="fa fa-eye"></i></a>&nbsp;&nbsp;
                                                <button  class="btn btn-danger" href="{{route('hr-employee-details.destroy',$dt['employee_id'])}}" title="Delete" data-toggle="tooltip" name="deleteEmployee"  ><i class="fa fa-trash"></i></button>
                                            </td>
                                        </tr> 
                                        @php($count++)
                                        @endforeach          
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
     </div>

    <script>
        $(document).ready(function() {
                        $('#dataTables-example').DataTable({
                        responsive: true,
                        dom: 'Bfrtip',
                        buttons: [
                            {
                            extend: 'excel',
                            text: 'Export As Exel',
                            title:'MIS Users',
                            className: 'btn btn-default',
                                // exportOptions: {
                                // columns: 'th:not(:last-child)'
                                // }
                            },
                             {
                            extend: 'copy',
                            text: 'Copy',
                            className: 'btn btn-default',
                                // exportOptions: {
                                // columns: 'th:not(:last-child)'
                                // }
                            },
                             {
                            extend: 'print',
                            text: 'Print',
                            title:'MIS uers',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'colvis',
                             text: 'Column Visibility',
                            className: 'btn btn-default',
                            columns: ':not(.noVis)',
                            }
                           ]
                });
    });
        $('button[name="deleteEmployee"]').on('click', function(e) {
            e.preventDefault();
            var url = $(this).attr('href');
            bootbox.confirm("Are you sure?", function(result) {
                if(result) {
                    $.ajax({
                        url:url,
                        type:'POST',
                        data : {"_token": "{{ csrf_token() }}","_method":"DELETE"},
                        success: function(res) {
                            bootbox.alert(res, function() {
                                location.reload();
                            });
                        }
                    });
                }
            });
        });
    </script>  
@endsection

resources/views/md-verification.blade.php
<!-- @extends('layouts.app') -->
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">MASTER DATA VERIFICATIONS</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group" role="group" aria-label="Basic example">
                        <a href="{{route('md-verification.create')}}" class="float-right btn-right">
                        <button type="button" class="btn btn-secondary" title="Add new user" data-original-title="Add New User">
                        <i class="fa fa-plus" aria-hidden="true"></i>ADD NEW DATA</button>
                        </a>
                    </div>    
                </div>   
            </div> 
            <div class="row">
                <div class="col-lg-12">
                @if (Session()->has('message'))
                <div class="alert alert-dismissable alert-success" id="flash-message">
                <button type="button"class="close"data-dismiss="alert"aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <strong>
               {{ Session::get('message') }}
                </strong>
                </div>
                @endif
                </div>
            </div>    
            <div class="row" style="min-height:800px;">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Officers in MIS
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Pen</th>
                                            <th>Region</th>
                                            <th>District</th>
                                            <th>Office name</th>
                                            <th>Cug</th>
                                             <th>Operations</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                            
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
     </div>
         
@endsection

resources/views/monthly-programs.blade.php
<!-- @extends('layouts.app') -->
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">MONTHLY PROGRAMS</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group" role="group" aria-label="Basic example">
                        <a href="{{route('monthly-programms.create')}}" class="float-right btn-right">
                        <button type="button" class="btn btn-secondary" title="Add new user" data-original-title="Add New User">
                        <i class="fa fa-plus" aria-hidden="true"></i>CREATE NEW PROGRAM</button>
                        </a>
                    </div>    
                </div>   
            </div> 
            <div class="row">
                <div class="col-lg-12">
                @if (Session()->has('message'))
                <div class="alert alert-dismissable alert-success" id="flash-message">
                <button type="button"class="close"data-dismiss="alert"aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <strong>
               {{ Session::get('message') }}
                </strong>
                </div>
                @endif
                </div>
            </div>    
            <div class="row" style="min-height:800px;">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                         MONTHLY PROGRAMS
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>District</th>
                                            <th>Camp</th>
                                            <th>Office</th>
                                            <th>Nature od duty</th>
                                            <th>Remarks</th>
                                             <th>Operations</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $dt)
                                    <tr class="odd gradeX">
                                        <td>{{$dt['date']}}</td>
                                        <td>{{$dt['district_name']}}</td>
                                        <td>{{$dt['camp']}}</td>
                                        <td>{{$dt['office_name']}}</td>
                                         <td>{{$dt['nature_of_duty']}}</td>
                                          <td>{{$dt['remarks']}}</td>
                                        <td>
                                            <a class="btn btn-default"    href="{{route('monthly-programms.edit',$dt['id'])}}"    title="Edit" data-toggle="tooltip"><i class="fa fa-edit "></i></a>&nbsp;&nbsp;
                                            <!-- <a class="btn btn-default"   href="{{route('users.show',$dt['id'])}}"    title="View" data-toggle="tooltip"><i class="fa fa-eye"></i></a>&nbsp;&nbsp; -->
                                            <button  class="btn btn-danger" href="{{route('monthly-programms.destroy',$dt['id'])}}" title="Delete" data-toggle="tooltip" name="deleteMonthlyPrograms"  ><i class="fa fa-trash"></i></button>
                                        </td>
                                    </tr> 
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
     </div>
     <script>
            $(document).ready(function() {
                $('#dataTables-example').DataTable({
                        responsive: true,
                        dom: 'Bfrtip',
                        buttons: [
                            {
                            extend: 'excel',
                            text: 'Export As Exel',
                            title:'Monthly program',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'copy',
                            text: 'Copy',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'print',
                            text: 'Print',
                            title:'Monthly program',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'colvis',
                             text: 'Column Visibility',
                            className: 'btn btn-default',
                            columns: ':not(.noVis)',
                            }
                           ]
                });

                $('button[name="deleteMonthlyPrograms"]').on('click', function(e) {
                    e.preventDefault();
                      var url = $(this).attr('href');
                    bootbox.confirm("Are you sure?", function(result) {
                         if(result) {
                         $.ajax({
                            url:url,
                            type:'POST',
                            data : {"_token": "{{ csrf_token() }}","_method":"DELETE"},
                            success: function(res) {
                                bootbox.alert(res, function() {
                                location.reload();
                                });
                            
                            }
                        });
                    }
                   
                  });
                });
            });
        </script>          
@endsection

resources/views/rtinewapplication.blade.php
<!-- @extends('layouts.app') -->
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">RTI APPLICATIONS</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group" role="group" aria-label="Basic example">
                        <a href="{{route('rti-new-application.create')}}" class="float-right btn-right">
                        <button type="button" class="btn btn-secondary" title="Add new user" data-original-title="Add New User">
                        <i class="fa fa-plus" aria-hidden="true"></i> CREATE NEW RTI APPLICATION</button>
                        </a>
                    </div>    
                </div>   
            </div> 
            <div class="row">
                <div class="col-lg-12">
                @if (Session()->has('message'))
                <div class="alert alert-dismissable alert-success" id="flash-message">
                <button type="button"class="close"data-dismiss="alert"aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <strong>
               {{ Session::get('message') }}
                </strong>
                </div>
                @endif
                </div>
            </div>    
            <div class="row" style="min-height:800px;">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            RTI Applications
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                        <th></th>
                                            <th>Name of applicant</th>
                                            <th>Address of applicant</th>
                                            <th>File Nmuber</th>
                                            <th>Mode of receipt</th>
                                            <th>Date id receipt</th>
                                            <th>Nature of information</th>
                                             <th>Nature of public</th>
                                             <th>Status</th>
                                             <th>Date of replay</th>
                                              <th>Act</th>
                                              <th>Date of rejection</th>
                                              <th>Rejection reason</th>
                                              <th>Amount released</th>
                                              <th>remarks</th>
                                             <th>Operations</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $dt)
                                    <tr class="odd gradeX">
                                    <td></td>
                                        <td>{{$dt['name_of_aplicant']}}</td>
                                        <td>{{$dt['address_of_aplicant']}}</td>
                                        <td>{{$dt['file_number']}}</td>
                                        <td class="center">{{$dt['mode_of_receipt']}}</td>
                                        <td class="center">{{$dt['date_of_receipt']}}</td> 
                                        <td class="center">{{$dt['nature_of_information']}}</td>
                                         <td class="center">{{$dt['nature_of_public']}}</td>
                                        <td class="center">{{$dt['status']}}</td>
                                        <td class="center">{{$dt['date_reply']}}</td>
                                        <td class="center">{{$dt['act']}}</td>
                                        <td class="center">{{$dt['date_rejection']}}</td>
                                        <td class="center">{{$dt['rejection_reason']}}</td>
                                        <td class="center">{{$dt['amount_released']}}</td>
                                        <td class="center">{{$dt['amount_released']}}</td>
                                        <td>
                                            <a class="btn btn-default"    href="{{route('rti-new-application.edit',$dt['id'])}}"    title="Edit" data-toggle="tooltip"><i class="fa fa-edit "></i></a>&nbsp;&nbsp;
                                            <!-- <a class="btn btn-default"   href="{{route('users.show',$dt['id'])}}"    title="View" data-toggle="tooltip"><i class="fa fa-eye"></i></a>&nbsp;&nbsp; -->
                                            <button  class="btn btn-danger" href="{{route('rti-new-application.destroy',$dt['id'])}}" title="Delete" data-toggle="tooltip" name="deleteRtiApplication"  ><i class="fa fa-trash"></i></button>
                                        </td>
                                    </tr> 
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
     </div>
              <script>
            $(document).ready(function() {
                        $('#dataTables-example').DataTable({
                        select: true,
                        responsive: true,
                        dom: 'Bfrtip',
                        
                        buttons: [
                            {
                            extend: 'excel',
                            text: 'Export As Exel',
                            title:'RTI New application',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)',
                                    modifier: {
                                    checked: true
                                    }
                                },
                            },
                             {
                            extend: 'copy',
                            text: 'Copy',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'print',
                            text: 'Print',
                            title:'RTI New application',
                            className: 'btn btn-default',
                                exportOptions: {
                                columns: 'th:not(:last-child)'
                                }
                            },
                             {
                            extend: 'colvis',
                             text: 'Column Visibility',
                            className: 'btn btn-default',
                            columns: ':not(.noVis)',
                            }
                           ],
                            'columnDefs': [
                            {
                            'targets': 0,
                            'checkboxes': {
                            'selectRow': true
                            }
                            }
                            ],
                            select: {
                            style:    'os',
                            selector: 'td:first-child',
                            'style': 'multi'
                            },
                            order: [[ 1, 'asc' ]]
                });

                $('button[name="deleteRtiApplication"]').on('click', function(e) {
                    e.preventDefault();
                      var url = $(this).attr('href');
                    bootbox.confirm("Are you sure?", function(result) {
                         if(result) {
                         $.ajax({
                            url:url,
                            type:'POST',
                            data : {"_token": "{{ csrf_token() }}","_method":"DELETE"},
                            success: function(res) {
                                bootbox.alert(res, function() {
                                location.reload();
                                });
                            
                            }
                        });
                    }
                   
                  });
                });
            });
        </script>    
@endsection